### ISSUE TITLE
Duplicate packages

### ISSUE THREAD

**Issue by steelbrain** [cdnjs/atom-extension#17]
Currently this repo is registered as both `cdnjs` and `cdnjs-atom-extension`. I believe this is a mistake, therefore you should unpublish either one of them.

**Comment by tairun** [comment]
What's worse they, are different versions:
![image](https://cloud.githubusercontent.com/assets/4248906/10753648/d9d687c2-7c92-11e5-9765-3d3badbb2cc7.png)

**Comment by PeterDaveHello** [comment]
ping @thomasdavis

**Comment by thomasdavis** [comment]
Any idea how to to figure out who is the author of the published package?

**Comment by thomasdavis** [comment]
Oh I think both are published by `cdnjs`

**Comment by thomasdavis** [comment]
Alright figured out how the damn things works. Cleared the other one and reset the main one -> https://atom.io/packages/cdnjs

Lost the download count which sucks

**Comment by thomasdavis** [comment]
Surprised the extension still works aha

**Comment by PeterDaveHello** [comment]
@thomasdavis let's add the link in readme

**Comment by thomasdavis** [comment]
Good idea, doing now.

On Fri, Feb 19, 2016 at 2:51 PM, Peter Dave Hello <notifications@github.com>
wrote:

> @thomasdavis <https://github.com/thomasdavis> let's add the link in readme
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cdnjs/atom-extension/issues/17#issuecomment-186040311>
> .
>



-- 
Thomas Davis
http://thomasdav.is

VP of Tech - Earbits - http://earbits.com
Co-founder - Cdnjs - http://cdnjs.com
Founder - Backbone Tutorials - http://backbonetutorials.com
