### ISSUE TITLE
Context menu entry

### ISSUE THREAD

**Issue by tairun** [cdnjs/atom-extension#18]
When right-clicking the "Download file from cdnjs" entry is also visible outside the tree-view. I thought the expected behavior was to only show it inside the tree-view, so I think the scope should be changed.

**Comment by ksprwhite** [comment]
this issue has been fixed on commit f3a29213eb24b7c47554e400f1741d013e060583

**Comment by thomasdavis** [comment]
Never thanked you for this one Kasper! Thanks!
