### ISSUE TITLE
Requesting angular cdn not working

### ISSUE THREAD

**Issue by MickelSierra85** [cdnjs/atom-extension#20]
Hi,

After typing Ctrl-alt-c, selecting Angular.js and typing 1.4.8, the following appears:
![image](https://cloud.githubusercontent.com/assets/15856973/11322761/71506274-9103-11e5-8e3e-2d42bb3773b8.png)

and when you press enter you see:
![image](https://cloud.githubusercontent.com/assets/15856973/11322765/9a7a93f4-9103-11e5-9a9d-a1b8d57593de.png)

and this does not work

**Comment by PeterDaveHello** [comment]
I guess the reason may be the changes of "filename" in angular.js, @thomasdavis what do you think?

**Comment by thomasdavis** [comment]
I can't replicate this error and it seems to work well with 2.x.x

**Comment by PeterDaveHello** [comment]
@MickelSierra85 do you still have this problem?
