### ISSUE TITLE
Final filenames not showing up

### ISSUE THREAD

**Issue by irrationalistic** [cdnjs/atom-extension#3]
All but the last menu will show content! I run the "geturl" method, find any library (such as "angularjs"), navigate to the proper version, and the menu after that is a list of blank items. When I pick one at random it will insert `//cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.0-beta.4/[object Object]`. Thoughts?

![screen shot 2015-02-16 at 5 53 43 pm](https://cloud.githubusercontent.com/assets/851856/6221741/d50f584a-b604-11e4-98c2-802c2edc523f.png)

**Comment by segphault** [comment]
This is now resolved.
