### ISSUE TITLE
Use the `atom-workspace` tag instead of the `workspace` class.

### ISSUE THREAD

**Issue by mykehowells** [cdnjs/atom-extension#6]
In keymaps/cdnjs.cson: Use the `atom-workspace` tag instead of the `workspace` class.

**Comment by IonicaBizau** [comment]
@thomasdavis This was fixed via #5. Can you :ship: a new version and close this?

**Comment by thomasdavis** [comment]
Will do.

**Comment by thomasdavis** [comment]
Done `1.5.2`
